version: "3.9"

services:
  companion-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  # Mount local data directory
    environment:
      - LLM_ENDPOINT=http://host.docker.internal:1234/v1/chat/completions
      - LLM_BASE_URL=http://host.docker.internal:1234/v1
